Imports AjaxControlToolkit

Partial Class Maintenance_TO_TODetail
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Dim qs As String = Request.QueryString(0)

        If qs = 0 Then
            If Not My.User.IsInRole("tourop_admin") Then
                Response.Redirect("~/Maintenance/TO/TO.aspx")
            Else
                dsAgencyDet.ChangeMode(DetailsViewMode.Insert)
            End If
        Else
            If Not My.User.IsInRole("tourop_admin") Then
                dsAgencyDet.Fields(dsAgencyDet.Fields.Count - 1).Visible = False
            End If
            'If Not ModificationRights.RightsSales Then
            '    dsAgencyDet.AutoGenerateEditButton = False
            '    dsAgencyDet.AutoGenerateInsertButton = False
            '    dsAgencyDet.AutoGenerateDeleteButton = False
            'End If
        End If
    End Sub

    Protected Sub dsAgencyDet_ItemDeleted(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.DetailsViewDeletedEventArgs) Handles dsAgencyDet.ItemDeleted
        If e.Exception IsNot Nothing Then
            popShow(False, "Error deleting TO", e.Exception.InnerException.Message)
            e.ExceptionHandled = True
        Else
            Response.Redirect("~/Maintenance/TO/TO.aspx")
        End If
    End Sub

    Protected Sub dsTODetail_Inserted(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.ObjectDataSourceStatusEventArgs) Handles dsTODetail.Inserted
        'Dim str As String = e.OutputParameters.Item("TourOpID")
        Dim str As String = e.OutputParameters.Item("NewID")

        If e.Exception IsNot Nothing Then
            popShow(False, "Error inserting TO", e.Exception.InnerException.Message)
            e.ExceptionHandled = True
        Else
            If Not (String.IsNullOrEmpty(str)) Then
                Dim proc As New TourOperTableAdapters.TourOpTableAdapter
                'Dim returnval As Integer
                'returnval = proc.UserAgenciesFix(Membership.GetUser.UserName, str)
                Response.Redirect(String.Format("TODetail.aspx?TOID={0}", str))
            End If
        End If
    End Sub

    Protected Sub LinkButton1_Click(ByVal sender As Object, ByVal e As System.EventArgs)
        dsAgencyDet.ChangeMode(DetailsViewMode.Insert)
    End Sub

    Protected Sub popShow(ByVal Question As Boolean, ByVal Title As String, ByVal Message As String)
        popMessage.Text = Message
        popLabel.Text = Title

        If Question Then
            btnYes.Visible = True
            btnNo.Text = "No"
        Else
            btnYes.Visible = False
            btnNo.Text = "OK"
        End If
        popExtender.Show()
    End Sub

    Protected Sub dsTODetail_Updated(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.ObjectDataSourceStatusEventArgs) Handles dsTODetail.Updated
        If e.Exception IsNot Nothing Then
            popShow(False, "Error editing TO", e.Exception.InnerException.Message)
            e.ExceptionHandled = True
        Else
            Me.dsAgencyDet.DataBind()
        End If
    End Sub

    Protected Sub dsAgencyDet_ItemInserting(sender As Object, e As DetailsViewInsertEventArgs) Handles dsAgencyDet.ItemInserting
        e.Values("Active") = True
    End Sub
End Class
